Multi_Library_new/Models/Album.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace Multi_Library.Models
{
    public partial class Album
    {
        public Album()
        {
            Songs = new HashSet<Song>();
        }

        public int Id { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public DateTime? DateCreate { get; set; }

        public virtual ICollection<Song> Songs { get; set; }
    }
}

Multi_Library_new/Controllers/AlbumController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Multi_Library.Interfaces;
using Multi_Library.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Security.Cryptography.X509Certificates;

namespace Multi_Library.Controllers
{
    public class AlbumController : Controller
    {
        private readonly Mul_Lib_Context Context;
        readonly IAlbum _ialbum;
        readonly ISong _isong;
        readonly IAuthorSong _iauthorSong;
        readonly IUserTable _iuserTable;
        readonly ICover _icover;


        public AlbumController(IAlbum ialbum, ISong isong, IAuthorSong iauthorSong,
            IUserTable iuserTable, ICover icover, Mul_Lib_Context context)
        {
            _ialbum = ialbum;
            _isong = isong;
            _iauthorSong = iauthorSong;
            _iuserTable = iuserTable;
            _icover = icover;
            Context = context;
        }

        public ViewResult AllAlbum()
        {
            var authorSongs = _iauthorSong.GetAll();
            var albums = _ialbum.GetAll();
            var albumCover = new List<AlbumCover>();

            foreach (var album in albums)
            {
                if (album != null)
                {
                    var albumSongs = _isong.GetAll().Where(song => song.AlbumId == album.Id).ToList();

                    var authorAlbumSongs = albumSongs.Where(song => authorSongs.Any(authorSong => authorSong.SongId == song.Id)).ToList();

                    if (authorAlbumSongs.Any())
                    {
                        Cover cover;
                        if (!authorAlbumSongs[0].CoverId.HasValue || _icover.GetById(authorAlbumSongs[0].CoverId.Value) == null)
                        {
                            cover = new Cover { Link = "/Covers/Нет_Альбома.jpg" };
                        }
                        else cover = _icover.GetById(authorAlbumSongs[0].CoverId.Value);

                        AlbumCover albumCoverCur = new AlbumCover
                        {
                            album = album,
                            cover = cover
                        };

                        albumCover.Add(albumCoverCur);
                    }
                }
            }

            var data = Tuple.Create(albumCover, _iuserTable);

            return View("AlbumsPage", data);
        }

        public ViewResult InfoAlbum(int albumId, int covertId)
        {
            var firstsong = _isong.GetAll().Where(x => x.AlbumId == albumId).First();
            var authorsong_s = _iauthorSong.GetAll().Where(x => x.SongId == firstsong.Id);
            var authors = new List<UserTable>();

            foreach (var authorsong in authorsong_s)
            {
                authors.Add(_iuserTable.GetById(authorsong.AuthorId));
            }

            //var album = _ialbum.GetAll().FirstOrDefault(x => x.Id == albumId);
            var album = _ialbum.GetById(albumId);
            var covertLink = _icover.GetById(covertId).Link;

            //foreach (var song in songs)
            //{
            //    if (_iauthorSong.GetAll().Any(x => x.SongId == song.Id))
            //    {
            //        var authorId = _iauthorSong.GetAll().FirstOrDefault(x => x.SongId == song.Id).AuthorId;
            //        authors.Add(_iuserTable.GetById(authorId));
            //    }
            //}

            var data = Tuple.Create(authors, album, covertLink);
            return View("AlbumPage", data);
        }

        public IActionResult CreateAlbumPage()
        {
            int userId = Convert.ToInt32(HttpContext.User.FindFirst("PersonId").Value);
            var user = _iuserTable.GetById(userId);

            if (user.UserType == 1)
            {
                var authors = _iuserTable.GetAll()
                .Where(x => x.Id != userId);
                //var songsByAuthor = _iauthorSong.GetAll()
                //    .Where(x => x.AuthorId == userId);
                //
                //var songs = new List<Song>();
                //foreach (var authorSong in songsByAuthor)
                //{
                //    var song = _isong.GetById(authorSong.SongId);
                //    if (song != null && song.AlbumId == null)
                //    {
                //        songs.Add(song);
                //    }
                //}
                var songs = Context.Get_author_singles(userId).AsEnumerable();

                var data = Tuple.Create(authors, songs);
                return View("CreateAlbumPage", data);
            }
            else
            {
                TempData["Message"] = "Создавать альбомы могут только авторы";
                return RedirectToAction("Index", "Home");
            }
        }

        public ViewResult EditAlbumPage(int albumID, int covertId)
        {
            var songs = _isong.GetAll().Where(x => x.AlbumId == albumID);
            var authors = new List<UserTable>();
            var album = _ialbum.GetAll().FirstOrDefault(x => x.Id == albumID);
            var cover = new Cover();
            if (covertId != 0)
            {
                cover = _icover.GetById(covertId);
            }
            else
            {
                cover.Link = "/Covers/Нет_Альбома.jpg";
            }
            foreach (var song in songs)
            {
                if (_iauthorSong.GetAll().Any(x => x.SongId == song.Id))
                {
                    var authorId = _iauthorSong.GetAll().FirstOrDefault(x => x.SongId == song.Id).AuthorId;
                    authors.Add(_iuserTable.GetById(authorId));
                }
            }

            var data = Tuple.Create(authors, album, cover);
            return View("EditAlbumPage", data);
        }
        public IActionResult CreateAlbum(string Name, string Description, int[] SelectedSongs, IFormFile AlbumCover)
        {
            if (SelectedSongs.Length < 2)
            {
                TempData["Message"] = "Вы не выбрали хотя бы две песни";
                return RedirectToAction("Index", "Home");
            }

            if (Name == null)
            {
                TempData["Message"] = "Вы не добавили название альбома";
                return RedirectToAction("Index", "Home");
            }

            var selectedSongIds = SelectedSongs.ToList();
            var selectedSongs = _isong.GetAll().Where(song => selectedSongIds.Contains(song.Id));

            var album = new Album
            {
                Name = Name,
                Description = Description,                
            };

            _ialbum.Add(album);

            int id = _ialbum.GetAll().Last().Id;



            foreach (var song in selectedSongs)
            {
                song.AlbumId = id;
                _isong.Update(song);
            }


            /*string uploadsFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot","Covers");
            string uniqueFileName = AlbumCover.FileName;
            string filePath = Path.Combine(uploadsFolder, uniqueFileName);

            using (var fileStream = new FileStream(filePath, FileMode.Create))
            {
                AlbumCover.CopyTo(fileStream);
            }

            string path = "/Covers/" + uniqueFileName;
            string coverFileUrl = Path.Combine(Path.GetDirectoryName(path), Path.GetFileName(path));*/

            int cid = Convert.ToInt32(selectedSongs.First().CoverId);
            var cover = new Cover
            {
                Link = _icover.GetById(cid).Link,
                //DatePut = DateTime.Now
            };

            //int count = _icover.GetAll().Where(x => x.Link == cover.Link).Count();
            _icover.Add(cover);

            int coverId = _icover.GetAll().Last().Id;
            foreach (var song in selectedSongs)
            {
                song.CoverId = coverId;
                _isong.Update(song);
            }
            
            return RedirectToAction("Index", "Home");
        }


        public IActionResult UpdateAlbum(int AlbumId, int CoverId, string Name, string Description, IFormFile cover)
        {
            var album = _ialbum.GetById(AlbumId);
            album.Name = Name;
            album.Description = Description;
            if(cover != null)
            {
                string uploadsFolder = Path.Combine(Directory.GetCurrentDirectory(), "Covers");
                string uniqueFileName = cover.FileName + ".jpg";
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    cover.CopyTo(fileStream);
                }

                string coverFileUrl = Path.Combine("/Covers", uniqueFileName);

                var coverChange = _icover.GetById(CoverId);
                coverChange.Link = coverFileUrl;
                _icover.Update(coverChange);
            }
            _ialbum.Update(album);
            return RedirectToAction("Index", "Home");
        }

        public IActionResult DeleteAlbum(int albumID)
        {
            var songs = _isong.GetAll().Where(x => x.AlbumId == albumID);
            foreach(var song in songs)
            {
                song.Album = null;
                song.AlbumId = null;
            }
            _ialbum.Delete(albumID);
            return RedirectToAction("Index", "Home");
        }
    }
}

Multi_Library_new/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Multi_Library.Interfaces;
using Multi_Library.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Multi_Library.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserTable _iuserTable;
        private readonly IAlbum _iAlbum;
        private readonly ICover _iCover;
        private readonly IAuthorSong _iAuthorSong;
        private readonly ISong _iSong;
        
        public UserController(IUserTable iuserTable, IAuthorSong authorSong, IAlbum album, ICover cover, IAuthorSong iAuthorSong, ISong isong)
        {
            _iuserTable = iuserTable;
            _iAlbum = album;
            _iCover = cover;
            _iAuthorSong = iAuthorSong;
            _iSong = isong;
        }

        public ViewResult AuthorInfo(int authorId)
        {
            var author = _iuserTable.GetById(authorId);

            var SongsAuthor = _iAuthorSong.GetAll().Where(x => x.AuthorId == authorId);
            var songs = new List<Song>();
            foreach (var songAuthor in SongsAuthor)
            {
                songs.Add(_iSong.GetById(songAuthor.SongId));
            }

            var albums = _iAlbum.GetAll().Where(album => album.Songs.Any(song => song.AuthorSongs.Any(author => author.AuthorId == authorId)));
            var coverAlbum = new List<CoverAlbum>();

            foreach (var album in albums)
            {
                if (album != null)
                {
                    var albumSongs = _iSong.GetAll().Where(song => song.AlbumId == album.Id).ToList();

                    var authorAlbumSongs = albumSongs.Where(song => SongsAuthor.Any(authorSong => authorSong.SongId == song.Id)).ToList();

                    if (authorAlbumSongs.Any())
                    {
                        Cover cover = _iCover.GetById(authorAlbumSongs[0].CoverId.Value);
                        if (cover == null)
                        {
                            cover = new Cover { Link = "/Covers/Нет_Альбома.jpg" };
                        }

                        CoverAlbum albumCoverCur = new CoverAlbum
                        {
                            Album = album,
                            Cover = cover
                        };

                        coverAlbum.Add(albumCoverCur);
                    }
                }
            }

            var data = Tuple.Create(author, songs, coverAlbum);

            return View("AuthorPage", data);
        }

        public ViewResult AllAuthors()
        {
            //var t = _iuserTable.GetAll().First();
            var authors = _iuserTable.GetAll().Where(x => x.UserType == 1);     
            var AuthorSong = _iAuthorSong.GetAll();
            foreach(var authorSong in AuthorSong)
            {
                authorSong.Author = _iuserTable.GetById(authorSong.AuthorId);
                authorSong.Song = _iSong.GetById(authorSong.SongId);
            }
            var data = Tuple.Create(AuthorSong, authors);

            return View("AuthorsPage", data);
        }
    }
}

Multi_Library_new/Views/Album/AlbumPage.cshtml
@using Multi_Library.Models;
@using Multi_Library.Interfaces;

@model Tuple<List<UserTable>, Album, string>
@{
    Layout = "_Layout";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Your Title</title>
    <link href="/css/AlbumPage.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="wrapper">
        <div class="album-head">
            <img src="@Model.Item3" />
            <div>
                <p>Название: @Model.Item2.Name</p>
                <p>Автора: </p>
                @{
                    @foreach (var authorName in Model.Item1)
                    {
                        <a href="@Url.Action("AuthorInfo", "User", new { authorId = authorName.Id })">@authorName.Name</a>
                    }
                }
            </div>
        </div>
        <div class="album-body">
            <h4 style="align-self: center; margin-top: 40px;">Песни входящие в альбом</h4>
            @{
                foreach (var song in Model.Item2.Songs)
                {
                    <div class="song-box">
                        <a href="@Url.Action("SongInformation", "Song", new { id = song.Id })">
                            <img class="song-img" src="@Model.Item3" />
                        </a>
                        <div>
                            <p>@song.Name</p>
                            <p>song.DatePut.ToShortDateString()</p>
                        </div>
                        <audio controls class="audio-player">
                            <source src="@song.Link" type="audio/mp3">
                        </audio>
                    </div>
                }
            }
        </div>
    </div>
</body>
</html>

Multi_Library_new/Views/Album/AlbumsPage.cshtml
@using Multi_Library.Models;
@using Multi_Library.Interfaces;

@model Tuple<List<AlbumCover>, IUserTable>
@{
    Layout = "_Layout";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Your Title</title>
    <link href="/css/AlbumsPage.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="wrapper">
        <h2 style="align-self: center">Все альбомы</h2>
        <div class="album-box">
            @{
                foreach (var obj in Model.Item1)
                {
                    var songs = obj.album.Songs.ToList();
                    var firstSong = songs.FirstOrDefault();

                    if (firstSong != null && firstSong.AuthorSongs != null && firstSong.AuthorSongs.Any())
                    {
                        var authorsLine = string.Join(", ", firstSong.AuthorSongs.Select(authorSong => Model.Item2.GetById(authorSong.AuthorId).Name));

                        <div class="album-cart">
                            <img src="@obj.cover.Link">
                            <p>Название: @obj.album.Name</p>
                            <p>Автора: @authorsLine</p>
                            <a href="@Url.Action("InfoAlbum", "Album", new { albumId = obj.album.Id, covertId = obj.cover.Id })">Детальніше</a>
                        </div>
                    }
                    else
                    {
                        <div class="album-cart">
                            <img src="@obj.cover.Link">
                            <p>Название: @obj.album.Name</p>
                            <p>Автора: </p>
                            <a href="@Url.Action("InfoAlbum", "Album", new { albumId = obj.album.Id, covertId = obj.cover.Id })">Детальніше</a>
                        </div>
                    }
                }
            }

        </div>
    </div>
</body>
</html>

Multi_Library_new/Views/Album/CreateAlbumPage.cshtml
@using Multi_Library.Models
@using Multi_Library.Interfaces
@model Tuple<IEnumerable<UserTable>, IEnumerable<Song>>

@{
    ViewData["Title"] = "Create Album";
    Layout = "_Layout";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create Album</title>
    <link href="/css/CreateAlbum.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="create-album-container" style="height: 100vh;">
        @using (Html.BeginForm("CreateAlbum", "Album", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            <h2>Создайте альбом</h2>

            <div class="form-group">
                <label asp-for="Name">Название</label>
                <input asp-for="Name" name="Name" class="form-control" required />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Description">Описание</label>
                <textarea asp-for="Description" name="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label>Выберите песни</label>
                <div class="song-grid">
                @foreach (var song in Model.Item2)
                {
                    <div>
                        <input asp-for="SelectedSongs" type="checkbox" name="SelectedSongs" value="@song.Id" />
                        <label asp-for="SelectedSongs">@song.Name</label>
                    </div>
                }
                </div>
            </div>

            /*<div class="form-group">
                <label>Выберите обложку</label>
                <input type="file" name="AlbumCover" class="form-control-file" />
            </div>*/

            <button type="submit" class="btn btn-primary">Создать альбом</button>
        }
    </div>
    <script>
        function validateForm() {
            var checkboxes = document.querySelectorAll('input[name="SelectedSongs"]:checked');
            if (checkboxes.length == 0) {
                alert('Выберите хотя бы одну песню!');
                return false;
            }
            return true;
        }
    </script>
</body>
</html>

Multi_Library_new/Views/Album/EditAlbumPage.cshtml
@using Multi_Library.Models;
@using Multi_Library.Interfaces;

@model Tuple<List<UserTable>, Album, Cover>
@{
    Layout = "_Layout";
}

<!DOCTYPE html>
<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Редактирование альбома</title>
    <link href="/css/AlbumPage.css" rel="stylesheet" type="text/css" />
    <link href="/css/EditAlbum.css" rel="stylesheet" type="text/css" />

</head>
<body>
    <div class="wrapperB">
        <div class="album-head">
            <img src="@Model.Item3.Link" />
            <div>
                <p>Название: @Model.Item2.Name</p>
                <p>Автора: </p>
                @{
                    foreach (var authorName in Model.Item1)
                    {
                        <a href="@Url.Action("AuthorInfo", "User", new { authorId = authorName.Id })">@authorName.Name</a>
                    }
                }
            </div>
        </div>
        <div class="album-body">
            @{
                foreach (var song in Model.Item2.Songs)
                {
                    <div class="song-box">
                        <a href="@Url.Action("SongInformation", "Song", new { id = song.Id })">
                            <img class="song-img" src="@Model.Item3.Link" />
                        </a>
                        <div>
                            <p>@song.Name</p>
                            <p>song.DatePut.ToShortDateString()</p>
                        </div>
                        <audio controls class="audio-player">
                            <source src="@song.Link" type="audio/mp3">
                        </audio>
                    </div>
                }
            }
        </div>
        <div class="edit-album-form">
            <h2>Редактировать информацию об альбоме</h2>
            @using (Html.BeginForm("UpdateAlbum", "Album", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()

                <input type="hidden" name="AlbumId" value="@Model.Item2.Id" />
                <input type="hidden" name="CoverId" value="@Model.Item3.Id" />


                <div class="form-group" style="margin-bottom: 40px;">
                    <label asp-for="Item2.Name">Название альбома</label>
                    <input asp-for="Item2.Name" value="@Model.Item2.Name" name="Name" class="form-control" required/>
                    <span asp-validation-for="Item2.Name" class="text-danger"></span>
                </div>

                <div class="form-group" style="margin-bottom: 40px;">
                    <label asp-for="Item2.Description">Описание альбома</label>
                    <textarea asp-for="Item2.Description"  name="Description" class="form-control">@Model.Item2.Description</textarea>
                    <span asp-validation-for="Item2.Description" class="text-danger"></span>
                </div>

                <div class="form-group" style="margin-bottom: 40px;">
                    <label>Выбрать обложку (jpg)</label>
                    <input type="file" name="AlbumCover" accept="image/jpeg">
                </div>

                <button type="submit" class="btn btn-primary">Сохранить изменения</button>
            }
            @using (Html.BeginForm("DeleteAlbum", "Album", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                <input type="hidden" name="albumId" value="@Model.Item2.Id"/>
                <button type="submit" class="btn btn-primary">Удалить альбом</button>
            }
        </div>
        </div>

</body>
</html>