Multi_Library_new/Models/VideoClip.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace Multi_Library.Models
{
    public partial class VideoClip
    {
        public VideoClip()
        {
           
        }

        public int Id { get; set; }
        public string Link { get; set; }
        public DateTime? DateCreate { get; set; }
        public int SongId { get; set; }

        public virtual Song Song { get; set; }
    }
}

Multi_Library_new/Controllers/SongController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Multi_Library.Interfaces;
using Multi_Library.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;

namespace Multi_Library.Controllers
{
    public class SongController : Controller
    {
        private readonly Mul_Lib_Context Context;
        private readonly ISong _isong;
        private readonly IAlbum _ialbum;
        private readonly ICover _icover;
        private readonly IAuthorSong _iauthorSong;
        private readonly IUserTable _iuserTable;
        private readonly IVideoClip _ivideoClip;
        //private readonly ISongSongPlaylist _isongSongPlayList;
        //private readonly IVideoClipClipPlaylist _ivideoClipClipPlaylist;

        public SongController(ISong isong, IAlbum ialbum, ICover icover, IAuthorSong iauthorSong,
            IUserTable iuser, IVideoClip ivideoClip, Mul_Lib_Context context)
        {
            _isong = isong;
            _ialbum = ialbum;
            _icover = icover;
            _iauthorSong = iauthorSong;
            _iuserTable = iuser;
            _ivideoClip = ivideoClip;
            Context = context;
            //_isongSongPlayList = songSongPlaylist;
            //_ivideoClipClipPlaylist = ivideoClipClipPlaylist;
        }

        public ViewResult SongView()
        {
            IEnumerable<Song> songs = _isong.GetAll();
            var data = Tuple.Create(songs, _ialbum, _icover);
            return View(data);
        }

        public ViewResult SongViewPage(int id)
        {
            var song = _isong.GetById(id);
            var data = Tuple.Create((IEnumerable<Song>)new List<Song> { song }, _ialbum, _icover);
            return View("SongView", data);
        }

        public IActionResult CreateSongPage()
        {
            int userId = Convert.ToInt32(HttpContext.User.FindFirst("PersonId").Value);
            var user = _iuserTable.GetById(userId);

            if (user.UserType == 1)
            {
                var authorSongs = _iauthorSong.GetAll();
                var albums = _ialbum.GetAll();
                var albumCover = new List<AlbumCover>();
                var authors = _iuserTable.GetAll()
                    .Where(x => x.UserType.ToString() == "Author"
                    && x.Id.ToString() != HttpContext.User.FindFirst("PersonId").Value);

                foreach (var album in albums)
                {
                    if (album != null)
                    {
                        var albumSongs = _isong.GetAll().Where(song => song.AlbumId == album.Id).ToList();

                        var authorAlbumSongs = albumSongs.Where(song => authorSongs.Any(authorSong => authorSong.SongId == song.Id)).ToList();

                        if (authorAlbumSongs.Any())
                        {
                            int cid = Convert.ToInt32(authorAlbumSongs[0].CoverId);
                            Cover cover = _icover.GetById(cid);
                            if (cover == null)
                            {
                                cover = new Cover { Link = "/Covers/Нет_Альбома.jpg" };
                            }

                            AlbumCover albumCoverCur = new AlbumCover
                            {
                                album = album,
                                cover = cover
                            };

                            albumCover.Add(albumCoverCur);
                        }
                    }
                }
                var data = Tuple.Create(albumCover, authors.ToList());

                return View("SongCreatePage", data);
            }
            else
            {
                TempData["Message"] = "Создавать песни могут только авторы";
                return RedirectToAction("Index", "Home");
            }
        }

            [HttpPost]
        public IActionResult CreateSong(Song model, int[] SelectedAuthors, IFormFile SongFile, IFormFile SongCoverfile)
        {

            if (SongFile == null)
            {
                TempData["Message"] = "Вы не добавили файл песни";
                return RedirectToAction("Index", "Home");
            }

            if (model.Name == null)
            {
                TempData["Message"] = "Вы не добавили название песни";
                return RedirectToAction("Index", "Home");
            }

            string sfilePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Songs", SongFile.FileName);
            using (var sfileStream = new FileStream(sfilePath, FileMode.Create))
            {
                SongFile.CopyTo(sfileStream);
            }
            string sLinkdemo = "/Songs/" + SongFile.FileName;
            string sLink = Path.Combine(Path.GetDirectoryName(sLinkdemo), Path.GetFileName(sLinkdemo));

            Cover cover;
            if (SongCoverfile != null)
            {
                string cfilePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Covers", SongCoverfile.FileName);
                using (var cfileStream = new FileStream(cfilePath, FileMode.Create))
                {
                    SongCoverfile.CopyTo(cfileStream);
                }
                string cLinkdemo = "/Covers/" + SongCoverfile.FileName;
                string cLink = Path.Combine(Path.GetDirectoryName(cLinkdemo), Path.GetFileName(cLinkdemo));

                cover = new Cover
                {
                    Link = cLink,
                    DateCreate = DateTime.Now
                };
                _icover.Add(cover);
            }
            else
            {
                if (!_icover.GetAll().Where(x =>
                x.Link == "/default-cover-art.png").Any())
                {
                    cover = new Cover
                    {
                        Link = "/default-cover-art.png",
                        DateCreate = DateTime.Now
                    };
                    _icover.Add(cover);
                }
            }
            //int count = _icover.GetAll().Where(x => x.Link == cover.Link).Count();
            //if (count == 0) _icover.Add(cover);
            int coverid = _icover.GetAll().LastOrDefault().Id;
            Song song;
            if (SongCoverfile != null)
            {
                song = new Song
                {
                    Name = model.Name,
                    Lyrics = model.Lyrics,
                    DateCreate = DateTime.Now,
                    CoverId = coverid,
                    Link = sLink
                };
            }
            else
            {
                song = new Song
                {
                    Name = model.Name,
                    Lyrics = model.Lyrics,
                    DateCreate = DateTime.Now,
                    CoverId = _icover.GetAll().ToList().Find(x => x.Link == "/default-cover-art.png").Id,
                    //Cover = cover,
                    Link = sLink
                };
            }
                _isong.Add(song);

            int songId = _isong.GetAll().Where(x => x.Name == song.Name).First().Id;
            var creatorSong = new AuthorSong
            {
                AuthorId = Convert.ToInt32(HttpContext.User.FindFirst("PersonId").Value),
                SongId = songId,
            };
            _iauthorSong.Add(creatorSong);
            foreach (var authorId in SelectedAuthors)
            {
                //if (!_iauthorSong.GetAll().Any(x => x.AuthorId == authorId && songId == x.SongId))
                //{
                var authorSong = new AuthorSong()
                {
                    AuthorId = authorId,
                    SongId = songId
                };
                _iauthorSong.Add(authorSong);
                //}
            }
            TempData["Message"] = "Песня создана";
            return RedirectToAction("Index", "Home");
        }
        public ViewResult SongEditPage(int id)
        {
            var song = _isong.GetById(id);
            var authorSongs = _iauthorSong.GetAll().Where(x => x.AuthorId.ToString() == HttpContext.User.FindFirst("PersonId").Value);     
             
            var songs = new List<Song>();
            foreach(var songId in authorSongs)
            {
                songs.Add(songId.Song);
            }
            var albums = _ialbum.GetAll();
            var albumList = new List<Album>();
            foreach (var album in albums)
            {
                if (album != null)
                {
                    var albumSongs = _isong.GetAll().Where(song => song.AlbumId == album.Id).ToList();

                    var authorAlbumSongs = albumSongs.Where(song => authorSongs.Any(authorSong => authorSong.SongId == song.Id)).ToList();

                    if (authorAlbumSongs.Any())
                    {
                        albumList.Add(album);
                    }
                }
            }
                var authors = _iauthorSong.GetAll().Where(x => x.SongId == song.Id);
            var authorIds = authors.Select(x => x.AuthorId);
            var authorNames = _iuserTable.GetAll().Where(user => authorIds.Contains(user.Id)).Select(user => user.Name).ToList();
            var videoClip = _ivideoClip.GetById(id);
            if (song.AlbumId != null)
            {
                song.Album = _ialbum.GetById(song.AlbumId.Value);
            }
            if (videoClip != null)
            {
                song.VideoClip = videoClip;
            }
            var data = Tuple.Create(song, albumList, _icover.GetAll().ToList(), authorNames);
            return View("EditSongPage", data);
        }

        public IActionResult UpdateSong(int songID, string SongName, string SongLyrics, int AlbumId, IFormFile SongFile)
        {
            var songForChange = _isong.GetById(songID);
            songForChange.Name = SongName;

Multi_Library_new/Controllers/VideoClipController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Multi_Library.Interfaces;
using Multi_Library.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace Multi_Library.Controllers
{
    public class VideoClipController : Controller
    {
        private readonly IVideoClip _ivideoClip;
        private readonly ISong _isong;
        private readonly IAuthorSong _iauthorSong;
        private readonly IUserTable _iuserTable;
        //private readonly IVideoClipClipPlaylist _playlistVideoClip;

        public VideoClipController(ISong isong, IVideoClip ivideoClip, IAuthorSong authorSong, IUserTable iuserTable)
        {
            _isong = isong;
            _ivideoClip = ivideoClip;
            _iuserTable = iuserTable;
            _iauthorSong = authorSong;
        }

        public ViewResult AllVideClips()
        {
            var videoclip = _ivideoClip.GetAll();
            foreach (var clip in videoclip) 
            {
                clip.Song = _isong.GetById(clip.SongId);
            }
            var data = Tuple.Create(videoclip);
            return View("VideClips", data);
        }

        public ViewResult InfoClip(int clipId)
        {
            var videoclip = _ivideoClip.GetById(clipId);
            videoclip.Song = _isong.GetById(videoclip.SongId);
            var data = Tuple.Create(videoclip);
            return View("VideoClipPage", data);
        }

        public IActionResult CreateVideoClipPage()
        {
            int userId = Convert.ToInt32(HttpContext.User.FindFirst("PersonId").Value);
            var user = _iuserTable.GetById(userId);

            if (user.UserType == 1)
            {
                var songsCreatedByCurrentUser = _isong.GetAll()
                .Where(song => _iauthorSong.GetAll().Any(authorSong =>
                    authorSong.SongId == song.Id && authorSong.AuthorId.ToString() ==
                    HttpContext.User.FindFirst("PersonId").Value)).ToList();

                var songsWithoutVideoClips = songsCreatedByCurrentUser
                    .Where(song => !_ivideoClip.GetAll().Any(clip => clip.SongId == song.Id))
                    .ToList();

                var data = Tuple.Create(songsWithoutVideoClips);
                return View("CreateVideoClip", data);
            }
            else
            {
                TempData["Message"] = "Создавать видеоклипы могут только авторы";
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [RequestFormLimits(ValueLengthLimit = int.MaxValue, MultipartBodyLengthLimit = int.MaxValue)]
        public IActionResult CreateVideoClip(int songId, IFormFile VideoClip)
        {
            if (VideoClip == null)
            {
                TempData["Message"] = "Вы не добавили файл видеоклипа";
                return RedirectToAction("Index", "Home");
            }

            string uploadsFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Video_Clip");
            string uniqueFileName = VideoClip.FileName;
            string filePath = Path.Combine(uploadsFolder, uniqueFileName);

            using (var fileStream = new FileStream(filePath, FileMode.Create))
            {
                VideoClip.CopyTo(fileStream);
            }

            string coverFileUrl = Path.Combine("/Video_Clip", uniqueFileName);

            var Clip = new VideoClip
            {
                SongId = songId,
                Link = coverFileUrl,
                DateCreate = DateTime.Now
            };
            _ivideoClip.Add(Clip);
            return RedirectToAction("Index", "Home");
        }

        public ViewResult EditVideoClipPage(int videoClipID)
        {
            //var videoClip = _ivideoClip.GetById(videoClipID);
            //videoClip.Song = _isong.GetById(videoClip.SongId);
            //
            //var songsCreatedByCurrentUser = _isong.GetAll()
            //    .Where(song => _iauthorSong.GetAll().Any(authorSong =>
            //        authorSong.SongId == song.Id && authorSong.AuthorId == UserTable.ActiveUser.Id))
            //    .ToList();
            //                                                                                                   fix this
            //var songsWithoutVideoClips = songsCreatedByCurrentUser
            //    .Where(song => !_ivideoClip.GetAll().Any(clip => clip.SongId == song.Id))
            //    .Where(song => song.Id != videoClipID)
            //    .ToList();
            //
            //var data = Tuple.Create(videoClip, songsWithoutVideoClips);
            return View();//return View("EditVideoClip", data);
        }
        public IActionResult UpdateVideoClip(int videoClipId, int SongId, IFormFile VideoClip)
        {
            var videoClip = _ivideoClip.GetById(videoClipId);
            videoClip.SongId = SongId;
            videoClip.Song = _isong.GetById(SongId);
            if(VideoClip != null)
            {
                string uploadsFolder = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Video_Clip");
                string uniqueFileName = VideoClip.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    VideoClip.CopyTo(fileStream);
                }

                string coverFileUrl = Path.Combine("/Video_Clip", uniqueFileName);
                videoClip.Link = coverFileUrl;
            }
            _ivideoClip.Update(videoClip);
            return RedirectToAction("Index", "Home");
        }

        public IActionResult DeleteVideoClip(int videoClipId)
        {
            //var removePlayList = _playlistVideoClip.GetAll().Where(x => x.VideoClipId == videoClipId);  
            //foreach(var removePlay in removePlayList)
            //{
            //    _playlistVideoClip.Delete(removePlay.VideoClipId, removePlay.ClipPlaylistId);                 fix this
            //}
            _ivideoClip.Delete(videoClipId);
            return RedirectToAction("Index", "Home");
        }
    }
}

Multi_Library_new/Views/VideoClip/CreateVideoClip.cshtml
@using Multi_Library.Models
@using Multi_Library.Interfaces

@model Tuple<List<Song>>

@{
    Layout = "_Layout";
}

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Create Video Clip</title>
    <link href="/css/CrateVidioClip.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="create-video-clip-container">
        @using (Html.BeginForm("CreateVideoClip", "VideoClip", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            @Html.AntiForgeryToken()
            <h2>Добавить видеоклип</h2>
            <div class="form-group">
                <label asp-for="Item1">Выберите песню</label>
                <select asp-for="Item1" class="form-control" name="songId" required>
                    <option value="">-- Выберите песню --</option>
                    @foreach (var song in Model.Item1)
                    {
                        <option value="@song.Id">@song.Name</option>
                    }
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Item2">Загрузите видео (формат MP4)</label>
                <input asp-for="Item2" type="file" name="VideoClip" accept=".mp4" class="form-control" required />
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Добавить видеоклип</button>
            </div>
        }
    </div>
</body>
</html>

Multi_Library_new/Views/VideoClip/EditVideoClip.cshtml
@using Multi_Library.Models;
@using Multi_Library.Interfaces;

@model Tuple<VideoClip, List<Song>>


@{
    Layout = "_Layout";
}

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Your Title</title>
    <link href="/css/VideoClipPage.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="wrapper">
        <video controls width="550" src="@Model.Item1.Link">
        </video>
        <div class="clip-info">
            <a href="@Url.Action("SongPageView", "Song", new { id = Model.Item1.SongId })"><h3>@Model.Item1.Song.Name</h3></a>
            <p>Дата загрузки: Model.Item1.DatePut.ToShortDateString()</p>
            <h3>Текст</h3>
            <p>@Html.Raw(Model.Item1.Song.Lyrics.Replace("\\n", "<br>"))</p>
        </div>
 
            <div class="edit-form">
            @using (Html.BeginForm("UpdateVideoClip", "VideoClip", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                <input type="hidden" name="videoClipId" value="@Model.Item1.Id" />
                <select asp-for="SongId" name="SongId" class="form-control" required>
                    <option value="@Model.Item1.SongId">@Model.Item1.Song.Name</option>
                    @foreach (var song in Model.Item2)
                    {
                        <option value="@song.Id">@song.Name</option>
                    }
                </select>
                <div class="form-group">
                    <label asp-for="Item2">Загрузите видео (формат MP4)</label>
                    <input asp-for="Item2" type="file" name="VideoClip" accept=".mp4" class="form-control" />
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Сохранить изменения</button>
                </div>
                }
            @using (Html.BeginForm("DeleteVideoClip", "VideoClip", FormMethod.Post))
            {
                <input type="hidden" name="videoClipId" value="@Model.Item1.Id" />
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Удалить</button>
                </div>
            }
        </div>
    </div>
</body>
</html>

Multi_Library_new/Views/VideoClip/VideClips.cshtml
@using Multi_Library.Models;
@using Multi_Library.Interfaces;

@model Tuple<IEnumerable<VideoClip>>


@{
    Layout = "_Layout";
}

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Your Title</title>
    <link href="/css/VideoClipsPage.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="wrapper">
        <h2 style="align-self: center">Все клипы</h2>
        <div class="clip-box">
            @{
                foreach (var obj in Model.Item1)
                {
                    <div class="clip-cart">
                        <video width="250" src="@obj.Link" start="10">
                        </video>
                        <a><h3>@obj.Song.Name</h3></a>
                        <p>Дата загрузки: obj.DatePut.ToShortDateString()</p>
                        <a href="@Url.Action("InfoClip", "VideoClip", new { clipId = obj.Id })" class="detail">Подробнее</a>
                    </div>
                }
            }

        </div>
    </div>
</body>
</html>

Multi_Library_new/Views/VideoClip/VideoClipPage.cshtml
@using Multi_Library.Models;
@using Multi_Library.Interfaces;

@model Tuple<VideoClip>


@{
    Layout = "_Layout";
}

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Your Title</title>
    <link href="/css/VideoClipPage.css" rel="stylesheet" type="text/css" />
</head>
<body>
    <div class="wrapper">
        <video controls width="550" src="@Model.Item1.Link">
        </video>
        <div class="clip-info">
            <a href="@Url.Action("SongViewPage", "Song", new { id = Model.Item1.SongId })"><h3>@Model.Item1.Song.Name</h3></a>
            <p>Дата загрузки: @Model.Item1.DateCreate</p>
            @{
            if (Model.Item1.Song.Lyrics != null)
            {
            <h3>Текст</h3>
            <p>@Html.Raw(Model.Item1.Song.Lyrics?.Replace("\\n", "<br>"))</p>
            }}
        </div>
    </div>
</body>
</html>