Multi_Library_new/Controllers/CoverController.cs
using Microsoft.AspNetCore.Mvc;
using Multi_Library.Interfaces;
using Multi_Library.Models;
using System;
using System.Collections.Generic;
using System.Linq;

namespace Multi_Library.Controllers
{
    public class CoverController : Controller
    {
        private readonly ICover _icover;
        private readonly IAlbum _ialbum;
        private readonly ISong _isong;
        
        public CoverController(ICover icover, IAlbum ialbum, ISong isong)
        {
            _icover = icover;
            _ialbum = ialbum;
            _isong = isong;
        }

        public ViewResult AllCovers()
        {
            //var coverAlbum = new List<CoverAlbum>();
            //foreach(var cover in _icover.GetAll())
            //{
            //    cover.Songs = _isong.GetAll().Where(x => x.CoverId == cover.Id).ToList();
            //}
            //foreach(var cover in _icover.GetAll())
            //{
            //    foreach (var song in cover.Songs)
            //    {
            //        if (song.AlbumId != null)
            //        {
            //            if (_ialbum.GetById(song.AlbumId.Value) != null)
            //            {
            //                var coverAlbumElem = new CoverAlbum
            //                {
            //                    Cover = cover,
            //                    Album = _ialbum.GetById(song.AlbumId.Value)
            //                };
            //                coverAlbum.Add(coverAlbumElem);
            //            }
            //        }
            //    }
            //}

            //var allcovers = _icover.GetAll();
            var allsongs = _isong.GetAll().ToList();
            foreach (var song in allsongs)
            {
                if (song.CoverId != null)
                {
                    int s = Convert.ToInt32(song.CoverId);
                    song.Cover = _icover.GetById(s);
                }

                if (song.AlbumId != null)
                {
                    int a = Convert.ToInt32(song.AlbumId);
                    song.Album = _ialbum.GetById(a);
                }
            }

            var allalbums = _ialbum.GetAll();
            foreach (var album in allalbums)
            {
                
            }
            var covers_albums = new List<CoverAlbum>();
            foreach (var album in allalbums) 
            {
                //int c;
                album.Songs = allsongs.Where(x => x.AlbumId == album.Id).ToList();
                if (album.Songs.Any())
                {
                    int cid = Convert.ToInt32(album.Songs.First().CoverId);
                    var cover_album = new CoverAlbum { Album = album, Cover = _icover.GetById(cid) };
                    covers_albums.Add(cover_album);
                }
            }

            var data = Tuple.Create(allsongs, covers_albums);
            return View("CoversPageView", data);
        }
    }
}

Multi_Library_new/Controllers/SongController.cs
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Multi_Library.Interfaces;
using Multi_Library.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;

namespace Multi_Library.Controllers
{
    public class SongController : Controller
    {
        private readonly Mul_Lib_Context Context;
        private readonly ISong _isong;
        private readonly IAlbum _ialbum;
        private readonly ICover _icover;
        private readonly IAuthorSong _iauthorSong;
        private readonly IUserTable _iuserTable;
        private readonly IVideoClip _ivideoClip;
        //private readonly ISongSongPlaylist _isongSongPlayList;
        //private readonly IVideoClipClipPlaylist _ivideoClipClipPlaylist;

        public SongController(ISong isong, IAlbum ialbum, ICover icover, IAuthorSong iauthorSong,
            IUserTable iuser, IVideoClip ivideoClip, Mul_Lib_Context context)
        {
            _isong = isong;
            _ialbum = ialbum;
            _icover = icover;
            _iauthorSong = iauthorSong;
            _iuserTable = iuser;
            _ivideoClip = ivideoClip;
            Context = context;
            //_isongSongPlayList = songSongPlaylist;
            //_ivideoClipClipPlaylist = ivideoClipClipPlaylist;
        }

        public ViewResult SongView()
        {
            IEnumerable<Song> songs = _isong.GetAll();
            var data = Tuple.Create(songs, _ialbum, _icover);
            return View(data);
        }

        public ViewResult SongViewPage(int id)
        {
            var song = _isong.GetById(id);
            var data = Tuple.Create((IEnumerable<Song>)new List<Song> { song }, _ialbum, _icover);
            return View("SongView", data);
        }

        public IActionResult CreateSongPage()
        {
            int userId = Convert.ToInt32(HttpContext.User.FindFirst("PersonId").Value);
            var user = _iuserTable.GetById(userId);

            if (user.UserType == 1)
            {
                var authorSongs = _iauthorSong.GetAll();
                var albums = _ialbum.GetAll();
                var albumCover = new List<AlbumCover>();
                var authors = _iuserTable.GetAll()
                    .Where(x => x.UserType.ToString() == "Author"
                    && x.Id.ToString() != HttpContext.User.FindFirst("PersonId").Value);

                foreach (var album in albums)
                {
                    if (album != null)
                    {
                        var albumSongs = _isong.GetAll().Where(song => song.AlbumId == album.Id).ToList();

                        var authorAlbumSongs = albumSongs.Where(song => authorSongs.Any(authorSong => authorSong.SongId == song.Id)).ToList();

                        if (authorAlbumSongs.Any())
                        {
                            int cid = Convert.ToInt32(authorAlbumSongs[0].CoverId);
                            Cover cover = _icover.GetById(cid);
                            if (cover == null)
                            {
                                cover = new Cover { Link = "/Covers/Нет_Альбома.jpg" };
                            }

                            AlbumCover albumCoverCur = new AlbumCover
                            {
                                album = album,
                                cover = cover
                            };

                            albumCover.Add(albumCoverCur);
                        }
                    }
                }
                var data = Tuple.Create(albumCover, authors.ToList());

                return View("SongCreatePage", data);
            }
            else
            {
                TempData["Message"] = "Создавать песни могут только авторы";
                return RedirectToAction("Index", "Home");
            }
        }

            [HttpPost]
        public IActionResult CreateSong(Song model, int[] SelectedAuthors, IFormFile SongFile, IFormFile SongCoverfile)
        {

            if (SongFile == null)
            {
                TempData["Message"] = "Вы не добавили файл песни";
                return RedirectToAction("Index", "Home");
            }

            if (model.Name == null)
            {
                TempData["Message"] = "Вы не добавили название песни";
                return RedirectToAction("Index", "Home");
            }

            string sfilePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Songs", SongFile.FileName);
            using (var sfileStream = new FileStream(sfilePath, FileMode.Create))
            {
                SongFile.CopyTo(sfileStream);
            }
            string sLinkdemo = "/Songs/" + SongFile.FileName;
            string sLink = Path.Combine(Path.GetDirectoryName(sLinkdemo), Path.GetFileName(sLinkdemo));

            Cover cover;
            if (SongCoverfile != null)
            {
                string cfilePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "Covers", SongCoverfile.FileName);
                using (var cfileStream = new FileStream(cfilePath, FileMode.Create))
                {
                    SongCoverfile.CopyTo(cfileStream);
                }
                string cLinkdemo = "/Covers/" + SongCoverfile.FileName;
                string cLink = Path.Combine(Path.GetDirectoryName(cLinkdemo), Path.GetFileName(cLinkdemo));

                cover = new Cover
                {
                    Link = cLink,
                    DateCreate = DateTime.Now
                };
                _icover.Add(cover);
            }
            else
            {
                if (!_icover.GetAll().Where(x =>
                x.Link == "/default-cover-art.png").Any())
                {
                    cover = new Cover
                    {
                        Link = "/default-cover-art.png",
                        DateCreate = DateTime.Now
                    };
                    _icover.Add(cover);
                }
            }
            //int count = _icover.GetAll().Where(x => x.Link == cover.Link).Count();
            //if (count == 0) _icover.Add(cover);
            int coverid = _icover.GetAll().LastOrDefault().Id;
            Song song;
            if (SongCoverfile != null)
            {
                song = new Song
                {
                    Name = model.Name,
                    Lyrics = model.Lyrics,
                    DateCreate = DateTime.Now,
                    CoverId = coverid,
                    Link = sLink
                };
            }
            else
            {
                song = new Song
                {
                    Name = model.Name,
                    Lyrics = model.Lyrics,
                    DateCreate = DateTime.Now,
                    CoverId = _icover.GetAll().ToList().Find(x => x.Link == "/default-cover-art.png").Id,
                    //Cover = cover,
                    Link = sLink
                };
            }
                _isong.Add(song);

            int songId = _isong.GetAll().Where(x => x.Name == song.Name).First().Id;
            var creatorSong = new AuthorSong
            {
                AuthorId = Convert.ToInt32(HttpContext.User.FindFirst("PersonId").Value),
                SongId = songId,
            };
            _iauthorSong.Add(creatorSong);
            foreach (var authorId in SelectedAuthors)
            {
                //if (!_iauthorSong.GetAll().Any(x => x.AuthorId == authorId && songId == x.SongId))
                //{
                var authorSong = new AuthorSong()
                {
                    AuthorId = authorId,
                    SongId = songId
                };
                _iauthorSong.Add(authorSong);
                //}
            }
            TempData["Message"] = "Песня создана";
            return RedirectToAction("Index", "Home");
        }
        public ViewResult SongEditPage(int id)
        {
            var song = _isong.GetById(id);
            var authorSongs = _iauthorSong.GetAll().Where(x => x.AuthorId.ToString() == HttpContext.User.FindFirst("PersonId").Value);     
             
            var songs = new List<Song>();
            foreach(var songId in authorSongs)
            {
                songs.Add(songId.Song);
            }
            var albums = _ialbum.GetAll();
            var albumList = new List<Album>();
            foreach (var album in albums)
            {
                if (album != null)
                {
                    var albumSongs = _isong.GetAll().Where(song => song.AlbumId == album.Id).ToList();

                    var authorAlbumSongs = albumSongs.Where(song => authorSongs.Any(authorSong => authorSong.SongId == song.Id)).ToList();

                    if (authorAlbumSongs.Any())
                    {
                        albumList.Add(album);
                    }
                }
            }
                var authors = _iauthorSong.GetAll().Where(x => x.SongId == song.Id);
            var authorIds = authors.Select(x => x.AuthorId);
            var authorNames = _iuserTable.GetAll().Where(user => authorIds.Contains(user.Id)).Select(user => user.Name).ToList();
            var videoClip = _ivideoClip.GetById(id);
            if (song.AlbumId != null)
            {
                song.Album = _ialbum.GetById(song.AlbumId.Value);
            }
            if (videoClip != null)
            {
                song.VideoClip = videoClip;
            }
            var data = Tuple.Create(song, albumList, _icover.GetAll().ToList(), authorNames);
            return View("EditSongPage", data);
        }

        public IActionResult UpdateSong(int songID, string SongName, string SongLyrics, int AlbumId, IFormFile SongFile)
        {
            var songForChange = _isong.GetById(songID);
            songForChange.Name = SongName;

Multi_Library_new/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Multi_Library.Interfaces;
using Multi_Library.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;

namespace Multi_Library.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserTable _iuserTable;
        private readonly IAlbum _iAlbum;
        private readonly ICover _iCover;
        private readonly IAuthorSong _iAuthorSong;
        private readonly ISong _iSong;
        
        public UserController(IUserTable iuserTable, IAuthorSong authorSong, IAlbum album, ICover cover, IAuthorSong iAuthorSong, ISong isong)
        {
            _iuserTable = iuserTable;
            _iAlbum = album;
            _iCover = cover;
            _iAuthorSong = iAuthorSong;
            _iSong = isong;
        }

        public ViewResult AuthorInfo(int authorId)
        {
            var author = _iuserTable.GetById(authorId);

            var SongsAuthor = _iAuthorSong.GetAll().Where(x => x.AuthorId == authorId);
            var songs = new List<Song>();
            foreach (var songAuthor in SongsAuthor)
            {
                songs.Add(_iSong.GetById(songAuthor.SongId));
            }

            var albums = _iAlbum.GetAll().Where(album => album.Songs.Any(song => song.AuthorSongs.Any(author => author.AuthorId == authorId)));
            var coverAlbum = new List<CoverAlbum>();

            foreach (var album in albums)
            {
                if (album != null)
                {
                    var albumSongs = _iSong.GetAll().Where(song => song.AlbumId == album.Id).ToList();

                    var authorAlbumSongs = albumSongs.Where(song => SongsAuthor.Any(authorSong => authorSong.SongId == song.Id)).ToList();

                    if (authorAlbumSongs.Any())
                    {
                        Cover cover = _iCover.GetById(authorAlbumSongs[0].CoverId.Value);
                        if (cover == null)
                        {
                            cover = new Cover { Link = "/Covers/Нет_Альбома.jpg" };
                        }

                        CoverAlbum albumCoverCur = new CoverAlbum
                        {
                            Album = album,
                            Cover = cover
                        };

                        coverAlbum.Add(albumCoverCur);
                    }
                }
            }

            var data = Tuple.Create(author, songs, coverAlbum);

            return View("AuthorPage", data);
        }

        public ViewResult AllAuthors()
        {
            //var t = _iuserTable.GetAll().First();
            var authors = _iuserTable.GetAll().Where(x => x.UserType == 1);     
            var AuthorSong = _iAuthorSong.GetAll();
            foreach(var authorSong in AuthorSong)
            {
                authorSong.Author = _iuserTable.GetById(authorSong.AuthorId);
                authorSong.Song = _iSong.GetById(authorSong.SongId);
            }
            var data = Tuple.Create(AuthorSong, authors);

            return View("AuthorsPage", data);
        }
    }
}

Multi_Library_new/Views/Shared/_Layout.cshtml
@using Multi_Library.Models;


<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/css/resize.css" rel="stylesheet" type="text/css" />
    <link href="~/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="~/css/Header.css" rel="stylesheet" type="text/css" />
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="~/js/bootstrap.min.js"></script> 
</head>
<body>
    <header>
        <div class="logo-box">
            <a class="logo" href="@Url.Action("Index", "Home")"> <img class="logo" src="/img/footer-logo.png" /> </a>
        </div>
        <div class="nav-bar">
            <a class="nav-a" href="@Url.Action("AllCovers", "Cover")">Обложки</a>
            <a class="nav-a" href="@Url.Action("AllAuthors", "User")">Автора</a>
            <a class="nav-a" href="@Url.Action("AllVideClips", "VideoClip")">Клипы</a>
            <a class="nav-a" href="@Url.Action("AllAlbum", "Album")">Альбомы</a>
            <a class="nav-a" href="@Url.Action("SongView", "Song")">Песни</a>
        </div>
        <div class="search-area">
            <form action="/Search/SerachByName" method="get">
                <input class="search-txt" type="text" name="searchWord" placeholder="Нажмите для поиска">
                <button type="submit" class="search-btn">Поиск</button>
            </form>
        </div>
        <div class="authefiaction-bar">

                    <a class="nav-a" href="@Url.Action("ProfilePage", "Account")">Профиль</a>
                    <a class="nav-a" href="@Url.Action("LoginPage", "Account")">Войти</a>
                    <a class="nav-a" href="@Url.Action("Logout", "Account")">Выйти</a>
                
                    <div class="dropdown">
                        <button id="dropdownMenu1" class="nav-a" data-toggle="dropdown" aria-haspopup="true">Меню</button>
                                <ul class="dropdown-content">
                               @{
                            // style="width: 120px; display: flex; justify-content: center; flex-wrap: wrap;" aria-labelledby="dropdownMenu1"
                                }
                                <li>
                                    <a href="@Url.Action("DeleteUsersPage", "Account")">Удалить пользователя</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("FavoriteSongs", "Account")">Избранные песни</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("MostPopularSongs", "Account")">Популярные песни</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("CreateSongPage", "Song")">Создать песню</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("CreateVideoClipPage", "VideoClip")">Создать клип</a>
                                </li>
                                <li>
                                    <a href="@Url.Action("CreateAlbumPage", "Album")">Создать альбом</a>
                                </li>
                            </ul>
                    </div>

        </div>
    </header>
    @if (TempData["Message"] != null)
    {

        <div id="alertMessage" class="alert alert-success">
            <strong>@TempData["Message"]</strong>
            <button type="button" class="close">&times;</button>

        </div>
    }
    <div>
        @RenderBody()
    </div>
    <footer>
        <div>
            <img src="~/img/footer-logo.png" alt="Footer Logo">
        </div>
    </footer>
    <script>
       $(document).ready(function () {
            $(".close").click(function () {
                $("#alertMessage").hide();
            });

            $("#dropdownMenu1").click(function () {
                $(".dropdown-content").toggle();
            });

            $(document).click(function (event) {
                var $target = $(event.target);
                if (!$target.closest('.dropdown').length && $('.dropdown-content').is(":visible")) {
                    $(".dropdown-content").hide();
                }
            });
        });
    </script>
</body>
</html>